timeout: 3600s
tags:
  - mongodb-on-gke-automation-main
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_REGION: ${GCP_REGION}
  _CLUSTER_NAME: ${CLUSTER_NAME}
  _CLUSTER_DOMAIN: ${CLUSTER_DOMAIN}
  _MACHINE_TYPE: ${MACHINE_TYPE}
  _CLUSTER_PROFILE: ${CLUSTER_PROFILE}

options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/cloud-builders/gcloud"
  id: "build-install-image"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --config=build-image/cloudbuild.yaml --substitutions=_PROJECT_ID=${_PROJECT_ID}

- name: "gcr.io/${_PROJECT_ID}/ci-cd-automation-installer"
  id: "create-cluster"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sed -i'' -e  "s/PROJECT_ID/${_PROJECT_ID}/g" terraform.tfvars
      sed -i'' -e  "s/GCP_REGION/${_GCP_REGION}/g" terraform.tfvars
      sed -i'' -e  "s/CLUSTER_NAME/${_CLUSTER_NAME}/g" terraform.tfvars
      sed -i'' -e  "s/CLUSTER_DOMAIN/${_CLUSTER_DOMAIN}/g" terraform.tfvars
      sed -i'' -e  "s/MACHINE_TYPE/${_MACHINE_TYPE}/g" terraform.tfvars

      terraform init
      terraform plan -out=terraform.tfplan
      terraform apply -auto-approve terraform.tfplan
  waitFor:
    - build-install-image

- name: "gcr.io/${_PROJECT_ID}/ci-cd-automation-installer"
  id: "install-mongodb-operator"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --config=modules/mongodb/cloudbuild.yaml --substitutions=\
      _PROJECT_ID=${_PROJECT_ID},\
      _GCP_REGION=${_GCP_REGION},\
      _CLUSTER_NAME=${_CLUSTER_NAME},\
      _CLUSTER_DOMAIN=${_CLUSTER_DOMAIN},\
      _CLUSTER_PROFILE=${_CLUSTER_PROFILE}
  waitFor:
    - create-cluster

- name: "gcr.io/${_PROJECT_ID}/ci-cd-automation-installer"
  id: "install-mongodb-exporter-prometheus"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --config=modules/mongodb-monitoring/cloudbuild.yaml --substitutions=\
      _PROJECT_ID=${_PROJECT_ID},\
      _GCP_REGION=${_GCP_REGION},\
      _CLUSTER_NAME=${_CLUSTER_NAME},\
      _CLUSTER_PROFILE=${_CLUSTER_PROFILE}
  waitFor:
    - install-mongodb-operator

- name: "gcr.io/${_PROJECT_ID}/ci-cd-automation-installer"
  id: "install-velero-backup-restore-mongodb"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --config=modules/mongodb-backup-restore/cloudbuild.yaml \
      --substitutions=_PROJECT_ID=${_PROJECT_ID},_GCP_REGION=${_GCP_REGION},_CLUSTER_NAME=${_CLUSTER_NAME}
  waitFor:
    - install-mongodb-exporter-prometheus
