timeout: 3600s # 1-hr
tags:
  - mongodb-on-gke-automation
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_REGION: ${GCP_REGION}
  _CLUSTER_NAME: ${CLUSTER_NAME}
  _CLUSTER_DOMAIN: ${CLUSTER_DOMAIN}
options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/${_PROJECT_ID}/ci-cd-automation-installer"
  id: "install-mongodb-operator"
  entrypoint: 'bash'
  args:
    - '-xe'
    - '-c'
    - |
      git clone https://github.com/Leisureroad/mongodb-kubernetes-operator.git

      cd mongodb-kubernetes-operator

      gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_GCP_REGION}

      # 使用PD-SSD作为默认的storage class, 并支持storage expansion
      kubectl patch sc standard -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
      kubectl patch sc premium-rwo -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

      kubectl create namespace mongodb

      # 创建CRD资源
      kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml

      # 查看CRD资源的创建
      kubectl get crd/mongodbcommunity.mongodbcommunity.mongodb.com

      # 创建role与role-bindings
      kubectl apply -k config/rbac/ --namespace mongodb

      # 查看资源的创建
      kubectl get role mongodb-kubernetes-operator --namespace mongodb
      kubectl get rolebinding mongodb-kubernetes-operator --namespace mongodb
      kubectl get serviceaccount mongodb-kubernetes-operator --namespace mongodb

      #TODO
      sed -i "s/YOUR_CLUSTER_DOMAIN/${_CLUSTER_DOMAIN}/" config/manager/manager.yaml
      #安装Operator
      kubectl create -f config/manager/manager.yaml --namespace mongodb

      #查看Operator创建
      kubectl get pods --namespace mongodb

      #TODO
      # 修改mongdb密码
      #sed -i "s/<your-password-here>/password/" config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml

      # 安装MongoDB集群
      kubectl apply -f config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml --namespace mongodb

      sleep 180

      kubectl get secret example-mongodb-admin-my-user -n mongodb -o json | jq -r '.data | with_entries(.value |= @base64d)'

      # cat value.yaml > /workspace/value.yaml
      # cat /workspace/value.yaml
      kubectl get mongodbcommunity --namespace mongodb
