tags:
  - mongodb-on-gke-automation
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'build-installer-image'
  args:
  - --destination=gcr.io/${_PROJECT_ID}/ci-cd-automation-installer
  - --cache=true
  - --cache-ttl=12h
